resilience4j.circuitbreaker:
  instances:
    notes:
      minimumNumberOfCalls: 5
      slowCallDurationThreshold: 1000ms

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      bindings:
        noteAddedEventConsumer-in-0:
          destination: notes-topic
          group: notes-event-queue

resilience4j.retry:
  instances:
    notes:
      maxAttemps: 3

