server:
  port: 8080
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/digis/IdeaProjects/microservices-demo/config-service/src/main/resources/config